name: CI/CD


on:
  push:
    paths:
      - Gemfile
      - Rakefile
      - lib/**
      - test/**
      - .github/workflows/build-gem.yml
      - fluent-plugin-slack.gemspec

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake

      - name: Release
        uses: jstastny/publish-gem-to-github@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: fluix